version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
      args:
        - NODE_ENV=development
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:9229:9229"
    command: yarn start:debug

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    ports:
      - "127.0.0.1:5432:5432"

  mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: development
      RABBITMQ_DEFAULT_PASS: development
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
